import type { WellnessEvent } from './types';

/**
 * Base reference coordinates used when generating event venue offsets.
 * Events are spread within a city-sized radius around this point.
 * The recommendation engine computes real distance from the user's GPS
 * location to each venue, so absolute coordinates only matter for spacing.
 */
const BASE_LAT = 51.5074;
const BASE_LNG = -0.1278;

/** Roughly 1km in degrees latitude. */
const KM = 1 / 111;

function hoursFromNow(hours: number): string {
  return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
}

function offset(latKm: number, lngKm: number) {
  return { lat: BASE_LAT + latKm * KM, lng: BASE_LNG + lngKm * KM };
}

export const EVENTS: WellnessEvent[] = [
  {
    id: 'e1',
    title: 'Restorative Yin Yoga',
    category: 'movement',
    intensity: 'restorative',
    tags: ['yoga', 'mindfulness', 'breathwork'],
    helpsWith: ['high-stress', 'poor-sleep', 'low-energy'],
    description:
      'A slow, grounding practice of long-held floor poses. Perfect for melting tension and resetting an overstimulated nervous system.',
    venue: 'Stillpoint Studio',
    ...offset(1.2, 0.8),
    startsAt: hoursFromNow(6),
    durationMin: 60,
    price: 12,
    groupSize: 'small',
    familyFriendly: false,
    imageColor: '#7fb5a8',
    registrationUrl: 'https://www.eventbrite.com/d/online/restorative-yin-yoga/',
  },
  {
    id: 'e2',
    title: 'Sunrise Park Run (5K)',
    category: 'outdoor',
    intensity: 'energizing',
    tags: ['running', 'fitness', 'nature', 'social'],
    helpsWith: ['low-mood', 'social-need'],
    description:
      'A friendly, all-paces community 5K through the park. Coffee and chat afterwards. Great for a morning mood boost.',
    venue: 'Greenfield Park',
    ...offset(-2.1, 1.5),
    startsAt: hoursFromNow(20),
    durationMin: 45,
    price: 0,
    groupSize: 'large',
    familyFriendly: true,
    imageColor: '#9bbf6f',
    registrationUrl: 'https://www.parkrun.org.uk/register/',
  },
  {
    id: 'e3',
    title: 'Guided Breathwork & Sound Bath',
    category: 'mind',
    intensity: 'restorative',
    tags: ['breathwork', 'meditation', 'mindfulness', 'music'],
    helpsWith: ['high-stress', 'poor-sleep'],
    description:
      'Deep diaphragmatic breathing followed by a calming sound bath with crystal bowls. Leave feeling deeply settled.',
    venue: 'The Calm Loft',
    ...offset(0.6, -1.1),
    startsAt: hoursFromNow(30),
    durationMin: 75,
    price: 18,
    groupSize: 'small',
    familyFriendly: false,
    imageColor: '#88a9c9',
    registrationUrl: 'https://www.eventbrite.com/d/online/breathwork-sound-bath/',
  },
  {
    id: 'e4',
    title: 'HIIT & Strength Bootcamp',
    category: 'movement',
    intensity: 'energizing',
    tags: ['fitness', 'social'],
    helpsWith: ['low-mood', 'social-need'],
    description:
      'High-intensity intervals and strength circuits to get the blood pumping and endorphins flowing.',
    venue: 'Forge Fitness',
    ...offset(2.4, 2.0),
    startsAt: hoursFromNow(10),
    durationMin: 50,
    price: 10,
    groupSize: 'large',
    familyFriendly: false,
    imageColor: '#d08a6a',
    registrationUrl: 'https://www.eventbrite.com/d/online/hiit-bootcamp/',
  },
  {
    id: 'e5',
    title: 'Mindful Watercolour Workshop',
    category: 'creative',
    intensity: 'restorative',
    tags: ['art', 'mindfulness'],
    helpsWith: ['high-stress', 'low-mood'],
    description:
      'No experience needed. A relaxed, process-over-product session that quiets the mind through gentle creativity.',
    venue: 'Open Studio Collective',
    ...offset(-1.0, -0.7),
    startsAt: hoursFromNow(48),
    durationMin: 120,
    price: 22,
    groupSize: 'small',
    familyFriendly: true,
    imageColor: '#c08fb5',
    registrationUrl: 'https://www.eventbrite.com/d/online/watercolour-workshop/',
  },
  {
    id: 'e6',
    title: 'Family Nature Walk & Forest Play',
    category: 'family',
    intensity: 'moderate',
    tags: ['nature', 'social'],
    helpsWith: ['low-mood', 'social-need', 'low-energy'],
    description:
      'A guided easy-going walk with nature games for all ages. Bring the kids — designed for families to unwind together.',
    venue: 'Ashwood Nature Reserve',
    ...offset(-3.2, -2.4),
    startsAt: hoursFromNow(36),
    durationMin: 90,
    price: 5,
    groupSize: 'large',
    familyFriendly: true,
    imageColor: '#6fae84',
    registrationUrl: 'https://www.eventbrite.com/d/online/family-nature-walk/',
  },
  {
    id: 'e7',
    title: 'Evening Slow Flow Yoga',
    category: 'movement',
    intensity: 'moderate',
    tags: ['yoga', 'breathwork', 'mindfulness'],
    helpsWith: ['high-stress', 'poor-sleep'],
    description:
      'A gentle, flowing sequence to release the day. Finishes with a long guided relaxation to prepare you for sleep.',
    venue: 'Lotus House',
    ...offset(0.9, 1.3),
    startsAt: hoursFromNow(12),
    durationMin: 60,
    price: 14,
    groupSize: 'small',
    familyFriendly: false,
    imageColor: '#8fb8a0',
    registrationUrl: 'https://www.eventbrite.com/d/online/slow-flow-yoga/',
  },
  {
    id: 'e8',
    title: 'Plant-Based Cooking Class',
    category: 'creative',
    intensity: 'moderate',
    tags: ['cooking', 'nutrition', 'social'],
    helpsWith: ['low-mood', 'social-need'],
    description:
      'Hands-on session cooking three nourishing seasonal dishes, then sharing a meal together with the group.',
    venue: 'The Kitchen Table',
    ...offset(1.8, -1.6),
    startsAt: hoursFromNow(54),
    durationMin: 120,
    price: 35,
    groupSize: 'small',
    familyFriendly: false,
    imageColor: '#d6a85f',
    registrationUrl: 'https://www.eventbrite.com/d/online/plant-based-cooking-class/',
  },
  {
    id: 'e9',
    title: 'Silent Meditation Sit',
    category: 'mind',
    intensity: 'restorative',
    tags: ['meditation', 'mindfulness'],
    helpsWith: ['high-stress', 'poor-sleep'],
    description:
      'A simple guided then silent sit suitable for beginners. A pocket of stillness in a busy week.',
    venue: 'City Meditation Centre',
    ...offset(0.3, 0.4),
    startsAt: hoursFromNow(26),
    durationMin: 40,
    price: 0,
    groupSize: 'small',
    familyFriendly: false,
    imageColor: '#9aa9c4',
    registrationUrl: 'https://www.eventbrite.com/d/online/silent-meditation/',
  },
  {
    id: 'e10',
    title: 'Ecstatic Dance Night',
    category: 'social',
    intensity: 'energizing',
    tags: ['dance', 'music', 'social'],
    helpsWith: ['low-mood', 'social-need', 'low-energy'],
    description:
      'A judgement-free dance floor — no steps, no alcohol, just movement and great music to shake off the week.',
    venue: 'The Movement Hall',
    ...offset(2.0, -0.9),
    startsAt: hoursFromNow(42),
    durationMin: 120,
    price: 15,
    groupSize: 'large',
    familyFriendly: false,
    imageColor: '#cf7fa8',
    registrationUrl: 'https://www.eventbrite.com/d/online/ecstatic-dance/',
  },
  {
    id: 'e11',
    title: 'Journalling & Tea Circle',
    category: 'mind',
    intensity: 'restorative',
    tags: ['reading', 'mindfulness', 'social', 'therapy'],
    helpsWith: ['high-stress', 'low-mood', 'social-need'],
    description:
      'Reflective prompts, quiet writing time and warm tea in a small, supportive circle. A soft place to land.',
    venue: 'The Reading Room',
    ...offset(-0.8, 0.9),
    startsAt: hoursFromNow(60),
    durationMin: 90,
    price: 8,
    groupSize: 'small',
    familyFriendly: false,
    imageColor: '#b59ad1',
    registrationUrl: 'https://www.eventbrite.com/d/online/journalling-tea-circle/',
  },
  {
    id: 'e12',
    title: 'Parent & Baby Gentle Movement',
    category: 'family',
    intensity: 'moderate',
    tags: ['yoga', 'fitness', 'social'],
    helpsWith: ['low-energy', 'social-need'],
    description:
      'Low-impact movement you can do alongside your little one, plus time to connect with other parents.',
    venue: 'Sunbeam Family Hub',
    ...offset(-1.6, 2.2),
    startsAt: hoursFromNow(28),
    durationMin: 50,
    price: 9,
    groupSize: 'small',
    familyFriendly: true,
    imageColor: '#7fc0b0',
    registrationUrl: 'https://www.eventbrite.com/d/online/parent-baby-movement/',
  },
  {
    id: 'e13',
    title: 'Trail Hike & Mindful Photography',
    category: 'outdoor',
    intensity: 'moderate',
    tags: ['nature', 'art', 'mindfulness'],
    helpsWith: ['low-mood', 'high-stress'],
    description:
      'A scenic group hike pausing to notice and photograph small details. Movement, fresh air and presence in one.',
    venue: 'Beacon Hill Trailhead',
    ...offset(-4.0, 1.0),
    startsAt: hoursFromNow(72),
    durationMin: 150,
    price: 0,
    groupSize: 'small',
    familyFriendly: true,
    imageColor: '#84ad6f',
    registrationUrl: 'https://www.eventbrite.com/d/online/trail-hike-photography/',
  },
  {
    id: 'e14',
    title: 'Sound Healing Deep Rest',
    category: 'mind',
    intensity: 'restorative',
    tags: ['meditation', 'music', 'breathwork'],
    helpsWith: ['poor-sleep', 'high-stress'],
    description:
      'Lie back under blankets and let layered gongs and bowls guide you into deep, restorative rest.',
    venue: 'Resonance Space',
    ...offset(0.5, -2.0),
    startsAt: hoursFromNow(16),
    durationMin: 60,
    price: 16,
    groupSize: 'large',
    familyFriendly: false,
    imageColor: '#8c9fce',
    registrationUrl: 'https://www.eventbrite.com/d/online/sound-healing-deep-rest/',
  },
  {
    id: 'e15',
    title: 'Community Garden Volunteering',
    category: 'outdoor',
    intensity: 'moderate',
    tags: ['nature', 'social', 'nutrition'],
    helpsWith: ['low-mood', 'social-need'],
    description:
      'Hands in the soil, good company and a sense of purpose. Tools and guidance provided, all welcome.',
    venue: 'Riverside Community Garden',
    ...offset(-2.6, -1.2),
    startsAt: hoursFromNow(34),
    durationMin: 120,
    price: 0,
    groupSize: 'large',
    familyFriendly: true,
    imageColor: '#9cc16f',
    registrationUrl: 'https://www.eventbrite.com/d/online/community-garden-volunteering/',
  },
];
